
from __future__ import absolute_import

from client.models.opp_dto import OppDto
from client.models.ms_channel_dto import MsChannelDto
from client.models.o_data_value_of_i_enumerable_of_opp_dto import ODataValueOfIEnumerableOfOppDto